version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./credentials.json:/app/credentials.json:ro
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - finance_network

networks:
  finance_network:
    driver: bridge